# Defines the options for building the project on linux with Travis-CI
# For more configuration options, see the wiki:
# https://github.com/craigcitro/r-travis/wiki/Porting-to-native-R-support-in-Travis

language: r
sudo: required
warnings_are_errors: true

before_install:
  - wget http://downloads.sourceforge.net/project/mcmc-jags/JAGS/3.x/Source/JAGS-3.4.0.tar.gz
  - tar xfvs JAGS-3.4.0.tar.gz
  - cd JAGS-3.4.0
  - sudo ./configure
  - sudo make
  - sudo make install
  - cd ..
  - sudo rm -f JAGS-3.4.0.tar.gz
  - sudo rm -rf JAGS-3.4.0
  
r_github_packages:
  - jimhester/covr
  - appling/unitted
  - USGS-R/streamMetabolizer
  - USGS-R/sbtools
  - USGS-R/geoknife

after_success:
  - Rscript -e 'covr::coveralls()'

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
