# Defines the options for building the project on linux with Travis-CI.
# For more configuration options, see the wiki:
# https://github.com/craigcitro/r-travis/wiki/Porting-to-native-R-support-in-Travis

language: r
r: release
sudo: required
warnings_are_errors: true

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

repos:
  CRAN: https://cran.rstudio.com
  GRAN: https://owi.usgs.gov/R
  
r_github_packages:
  - jimhester/covr
  - USGS-R/streamMetabolizer@develop

after_success:
  - Rscript -e 'covr::coveralls()'

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
