
environment:
  R_CHECK_ARGS: --no-build-vignettes --no-manual --no-multiarch
  R_BUILD_ARGS: --no-build-vignettes --no-manual
  R_INSTALL_ARGS: --no-multiarch
  GITHUB_PAT: 
    secure: qm2NVTPZnskxmmfSgZ/28XSSOKqIWja5Kc+XKSd8BsHwoeo/DXq+rUOZgKc3YtRv
  CRAN: 'http://cran.rstudio.com",GRAN="http://owi.usgs.gov/R'

init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/aappling-usgs/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

build_script:
  - R --version
  - travis-tool.sh install_github USGS-R/dataRetrieval USGS-R/sbtools appling/unitted USGS-R/streamMetabolizer
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
